<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DB;
use PDF;
use App\Patient;
use App\User;


class PatientPDFController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    function index()
    {
        $patient_data=$this->get_patient_data();
        return view('Patient_pdf')->with('patient_data',$patient_data);

    }

    function get_patient_data()
    {
        $patient_data=DB::table('patients')
        ->limit(30)
        ->get();

        return $patient_data;
    }

    function pdf()
    {
        $pdf=\App::make('dompdf.wrapper');
        $pdf->loadHTML($this->convert_patient_data_to_html());
        return $pdf->stream();
    }

    function convert_patient_data_to_html()
    {
        $patient_data= $this->get_patient_data();

        $output='
        <img src="images/main/mainlayout/logo_dark_long.png" alt="">
        <hr>

        <h2 align="center" style="color:#201D1E">Registered Patients</h2>
       <table style="border-collapse:collapse;border=0px;">

        <tr align="center">
            <th width = "100px" style="border: 1px solid">patientID</th>
            <th  width = "100px" style="border: 1px solid">Name</th>
            <th width = "100px" style="border: 1px solid">DOB</th>
            <th width = "100px" style="border: 1px solid">NIC</th>
            <th width = "100px" style="border: 1px solid">Phone</th>
            <th width = "100px" style="border: 1px solid">Email</th>
        
        
        </tr>
        ';

        foreach ($patient_data as $patient)
        {
            $output .= '
            
    <tr align="center" >
<td style="padding-top:.5em;padding-bottom:.5em;border: 1px solid;font-weight: bold">'.$patient->patient_id.'</td>
<td style="padding-top:.5em;padding-bottom:.5em;border: 1px solid">'.$patient->fullname.'</td>
<td style="padding-top:.5em;padding-bottom:.5em;border: 1px solid">'.$patient->dob.'</td>
<td style="padding-top:.5em;padding-bottom:.5em;border: 1px solid">'.$patient->nic.'</td>
<td style="padding-top:.5em;padding-bottom:.5em;border: 1px solid">'.$patient->phone.'</td>
<td style="padding-top:.5em;padding-bottom:.5em;border: 1px solid">'.$patient->email.'</td>

    </tr>
            
            
            ';
        }

        $output .= '
        </table>
        <hr>
        <p><i>This is a certified copy and doesnt require any signature <i></p>
        <p><em>report generated by Vidula admin department</em></p>
        ';
        return $output;
    }

    //table 2

    public function search_user()
    {
        $final=Auth::user();
        
        $result = DB::table('patients')->where('email', $final->email)->first();
        return $result;
    }

    public function pdf_profile()
    {
           
        $pdf = \App::make('dompdf.wrapper');
        $pdf -> loadHTML($this->user_profile_to_html());
        return $pdf->stream();
    }

    public function user_profile_to_html()
    {
        $patient_data = $this->search_user();
        $output = '
        <img src="images/main/mainlayout/logo_dark_long.png" alt="">
        <hr>
        <h2 align="center" style="style="color:#201D1E;">Account Information of '.$patient_data->fullname.'</h2>

        <table>
        <tr>
        <td style="padding-right:100px;padding-top:.5em;padding-bottom:.5em;font-weight: bold">Patient reference ID</td>
        <td>'.$patient_data->patient_id.'</td>
        </tr>

        <tr>
        <td style="padding-right:100px;padding-top:.5em;padding-bottom:.5em;font-weight: bold">Full name</td>
        <td>'.$patient_data->fullname.'</td>
        </tr>

        <tr>
        <td style="padding-right:100px;padding-top:.5em;padding-bottom:.5em;font-weight: bold">Gender</td>
        <td>'.$patient_data->gender.'</td>
        </tr>

        <tr>
        <td style="padding-right:100px;padding-top:.5em;padding-bottom:.5em;font-weight: bold">Date of Birth</td>
        <td>'.$patient_data->dob.'</td>
        </tr>

        <tr>
        <td style="padding-right:100px;padding-top:.5em;padding-bottom:.5em;font-weight: bold">National Identity Number</td>
        <td>'.$patient_data->nic.'</td>
        </tr>

        <tr>
        <td style="padding-right:100px;padding-top:.5em;font-weight: bold">Full address</td>
        <td>'.$patient_data->address1.'</td>
        </tr>

        <tr>
        <td></td>
        <td>'.$patient_data->address2.'</td>
        </tr>

        <tr>
        <td></td>
        <td>'.$patient_data->city.'</td>
        </tr>

        <tr>
        <td></td>
        <td style="padding-bottom:.5em;">Sri Lanka</td>
        </tr>

        <tr>
        <td style="padding-right:100px;padding-top:.5em;padding-bottom:.5em;font-weight: bold">Phone Number</td>
        <td>'.$patient_data->phone.'</td>
        </tr>

        <tr>
        <td style="padding-right:100px;padding-top:.5em;padding-bottom:.5em;font-weight: bold">Email Address</td>
        <td>'.$patient_data->email.'</td>
        </tr>


        </table>
        <hr>
        <p><i>**This is a system generated report and does not require a signature<i></p>
        <p><em>**This report can be used as a source of proof</em></p>
              
        ';
                        
        
        return $output;
    }

}
