<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\payment;

use PDF;

use DB;

class PaymentReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $payments = payment::latest()->paginate(30);
        return view('payment.paymentReport', compact('payments'))
                 ->with('i', (request() -> input ('page', 1)-1)*10);
    }

    public function get_payment_data()
    {
     $payment_data = DB::table('payments')
         ->limit(30)
         ->get();
     return $payment_data;
    }

    public function get_card_data()
    {
     $payment_data = DB::table('cards')
         ->limit(30)
         ->get();
     return $payment_data;
    }

    public function search_payment_data($patientID)
    {
     $payment_data = payment::latest()->where('patientID', 'like', '%'.$patientID.'%')->paginate(10);
     return $payment_data;
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    public function pdf()
    {
        $pdf = \App::make('dompdf.wrapper');
        $pdf -> loadHTML($this->payment_details_to_html());
        return $pdf->stream();
    }
    public function pdf_card()
    {
        $pdf = \App::make('dompdf.wrapper');
        $pdf -> loadHTML($this->card_details_to_html());
        return $pdf->stream();
    }

    public function pdf_search(Request $request)
    {
        $patientID = $request->get('patientID');   
        $pdf = \App::make('dompdf.wrapper');
        $pdf -> loadHTML($this->payment_search_to_html($patientID));
        return $pdf->stream();
    }

    public function payment_details_to_html()
    {
        $payment_data = $this->get_payment_data();
        $output = '
        <img src="images/main/mainlayout/logo_dark_long.png"> 
        <h3 align="center"><b>REPORT:</b>Payment Details(CASHIER)</h3>
        <h5 align="right"><i>Generated by Cashier</i></h5>
                <table width="100%" style="border-collapse: collapse; border: 0px;">
                    <tr>
                    <th style="border: 1px solid; padding:12px;" width = "50px"><b>Pay ID</b></th>
                    <th style="border: 1px solid; padding:12px;" width = "100px">Patient ID</th>
                    <th style="border: 1px solid; padding:12px;" width = "150px">Payment For</th>
                    <th style="border: 1px solid; padding:12px;" width = "120px">Amount(LKR.)</th>
                    <th style="border: 1px solid; padding:12px;" width = "150px">Date</th>
                    
                    </tr>
                    <br>
        ';
                        
        foreach ($payment_data as $payment) 
        {
            $output .= '
                <tr>
                    <td style="border: 1px solid; padding:12px;"><b>'.$payment -> id.'</b></td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->patientID.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->paymentFor.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->amount.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->date.'</td>
                </tr>
            ';
        }
        
        $output .= '</table>
        
        <h4 align = "center"><i>*Only for office use, <mark>CONFIDENTIAL DOCUMENT</mark>*</i></h4>
        ';
        return $output;
    }

    public function card_details_to_html()
    {
        $payment_data = $this->get_card_data();
        $output = '
        <img src="images/main/mainlayout/logo_dark_long.png">
        <h3 align="center"><b>REPORT:</b>Card Payment Details</h3>
        <h5 align="right"><i>Generated by Cashier</i></h5>
                <table width="100%" style="border-collapse: collapse; border: 0px;">
                    <tr>
                    <th style="border: 1px solid; padding:12px;" width = "100px"><b>Card Pay ID</b></th>
                    <th style="border: 1px solid; padding:12px;" width = "80px">Patient ID</th>
                    <th style="border: 1px solid; padding:12px;" width = "80px">Order ID</th>
                    <th style="border: 1px solid; padding:12px;" width = "120px">Card Number</th>
                    <th style="border: 1px solid; padding:12px;" width = "100px">Bank</th>
                    <th style="border: 1px solid; padding:12px;" width = "90px">Card Type</th>
                    
                    </tr>
                    <br>
        ';
                        
        foreach ($payment_data as $payment) 
        {
            $output .= '
                <tr>
                    <td style="border: 1px solid; padding:12px;"><b>'.$payment -> id.'</b></td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->patientID.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->orderID.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->cardNum.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->bank.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->cardType.'</td>
                </tr>
            ';
        }
        
        $output .= '</table>
        <h4 align = "center"><i>*Only for office use, <mark>CONFIDENTIAL DOCUMENT</mark>*</i></h4>
        ';
        return $output;
    }
    
    public function payment_search_to_html($patientID)
    {
        $payment_data = $this->search_payment_data($patientID);
        $output = '
        <img src="images/main/mainlayout/logo_dark_long.png">
        <h3 align="center"><b>REPORT:</b>Payment Details For '.$patientID.'</h3>
        <h5 align="right"><i>Generated by Cashier</i></h5>
                <table width="100%" style="border-collapse: collapse; border: 0px;">
                    <tr>
                    <th style="border: 1px solid; padding:12px;" width = "50px"><b>Pay ID</b></th>
                    <th style="border: 1px solid; padding:12px;" width = "100px">Patient ID</th>
                    <th style="border: 1px solid; padding:12px;" width = "150px">Payment For</th>
                    <th style="border: 1px solid; padding:12px;" width = "100px">Amount(LKR.)</th>
                    <th style="border: 1px solid; padding:12px;" width = "100px">Date</th>
                    
                    </tr>
                    <br>
        ';
                        
        foreach ($payment_data as $payment) 
        {
            $output .= '
                <tr>
                    <td style="border: 1px solid; padding:12px;"><b>'.$payment -> id.'</b></td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->patientID.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->paymentFor.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->amount.'</td>
                    <td style="border: 1px solid; padding:12px;">'.$payment->date.'</td>
                </tr>
            ';
        }
        
        $output .= '</table>
        <h4 align = "center"><i>*Only for office use, <mark>CONFIDENTIAL DOCUMENT</mark>*</i></h4>
        ';
        return $output;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
